### ISSUE TITLE
Failed to activate the mojave-dark-mode package

### ISSUE THREAD

**Issue by phl59** [paysonwallach/auto-dark-mode#1]
Failed to activate the mojave-dark-mode package
systemPreferences.subscribeNotification is not a function
Hide Stack Trace
TypeError: systemPreferences.subscribeNotification is not a function
    at Object.activate (C:\Users\ph59l\.atom\packages\mojave-dark-mode\dist\main.js:33:23)
    at Package.activateNow (<embedded>:75166:33)
    at measure (<embedded>:75142:33)
    at Package.measure (<embedded>:75024:25)
    at activationPromise.Promise (<embedded>:75136:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:75134:38)
    at PackageManager.activatePackage (<embedded>:26276:42)
    at config.transactAsync (<embedded>:26251:36)
    at Config.transactAsync (<embedded>:22810:28)
    at PackageManager.activatePackages (<embedded>:26249:23)
    at PackageManager.activate (<embedded>:26228:50)
    at loadStatePromise.loadState.then (<embedded>:1118:27)
    at <anonymous>:null:null

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [mojave-dark-mode](https://github.com/paysonwallach/mojave-dark-mode) package 0.2.3

### Stack Trace

Failed to activate the mojave-dark-mode package

```
At systemPreferences.subscribeNotification is not a function

TypeError: systemPreferences.subscribeNotification is not a function
    at Object.activate (/packages/mojave-dark-mode/dist/main.js:33:23)
    at Package.activateNow (<embedded>:75166:33)
    at measure (<embedded>:75142:33)
    at Package.measure (<embedded>:75024:25)
    at activationPromise.Promise (<embedded>:75136:20)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:75134:38)
    at PackageManager.activatePackage (<embedded>:26276:42)
    at config.transactAsync (<embedded>:26251:36)
    at Config.transactAsync (<embedded>:22810:28)
    at PackageManager.activatePackages (<embedded>:26249:23)
    at PackageManager.activate (<embedded>:26228:50)
    at loadStatePromise.loadState.then (<embedded>:1118:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.16 
autumn-highlighter-syntax 1.13.0 
dark-mode 3.0.0 
french-menu 0.2.2 
Hydrogen 2.6.0 
mojave-dark-mode 0.2.3 
styri-syntax 0.2.0 
```

**Comment by paysonwallach** [comment]
Hello, from the looks of it, this issue is a result of using the package on an OS that is not macOS. I've added a process check on that will prevent it from attempting to activate on non-Darwin systems.
